* 5/15/2019 @ Raven's Nest
Really need to work on kills
** 0-2 vs YugiX (diddy)
Diddy could only kill with the banana setup, but I couldn't reliably kill
him either. 

Dash back is overpowered against me. I love to run in from any spacing --
including really far away. It's super telegraphed and I need to figure out
tricks or better options. Don't make your goal something as nebulous as "figure
out good approach options". Instead:
What's a good range to do the low percent nair?
Work on floating in center stage -> last minute fair or high nair
Close fadeback fair -> dtilt

** 0-2 vs ProKitten (wii fit + doc)
I don't even remember this game super well. He didn't trick me blatantly or
overwhelm me, I just felt like I made dumb mistakes and he punished for them. 

Game 1 I did a dumb jump out fair on a high recovery and I got spiked for it. 

He loved to roll from ledge, but I missed a lot of my backair reactions on
that. 

Doc hits harder than you expect. 
* 5/23/2019 @ RAR
** 0-2 vs Avinia
Never jump out of Ike's combos. uair will still reach you and you'll die. 
watch out for how ike mixes up tomahawk, sh nair, full hop nair that hits
behind, and jabs. 
** 0-2 vs Spiral Distora
Literally felt like I couldn't do anything. He played YL. I tried to camp so I
could get waft, but he kept hitting me with every projectile. Not sure what he
was even calling out, got really tilted. I need to work on evading projectiles
more. 
* 5/29/2019 @ Raven's Nest
** 1-2 vs Fallen
Destroyed his ZSS game 1. Make sure you hit your techs against ZSS so she
doesn't get totally free tech chases against you. 

Mega Man is hard. I have no idea how to deal with Leaf Shield. Rolling seemed to
do pretty good. 

Camping worked well, but I took a fair amount of damage doing it
in game 2. 

I got a lot of kills off of reading his ledge options (b-air his neutral get
up). 

He caught me several times air dodging into u-smash. 

His landing b-air is really safe

Watch how much you jump when you recover because he can call it out pretty
easily with f-air. 
** 0-2 vs Malibu JoneZ
I need to learn how to edge guard Incineroar. 

Don't do those panic dash attacks don't do them for real for real so much it
totally lost you the set. Pretty sure I would have won that set if not for
those. 

He was just mixing up his ledge options between neutral get up and roll, but I
still had trouble covering it. 

Watch out for revenge on Waft :( Can you camp out revenge?

I did well catching him try to take space. 
* 6/3/2019  @ Tech Chase
** 1-2 vs Chance
This was a really close set. I'm not 100% sure what I fucked up here. My punish
was really good. He wanted to go for a lot of dash attack so I did run up shield
a lot. I think that if one of two things was better, I would have won:
1) Ledge trapping
2) Edgeguarding

I'm hesitant to edgeguard DK because he has a bunch of spikes that will catch
you off guard. 
** 0-2 vs Switch
This was a pretty dumb set. He played Snake. First game I had a nice lead but I
SD'd last stock. I have this problem against Snake where I want to camp for
Waft, but it's really hard to land full waft. Pretty much the only way I know
how is to get a falling up-air, but that isn't an easy move to get, especially
when they know it's coming. If I can work on that + doing Tweek bike edgeguards,
I think the Snake matchup will improve a lot. 
* 9/15/2019 @ We Tech Those
** 2-0 vs JellyTarzan
Charizard reallllly wants to hit you out of his shield. So don't let him. Get
those low up-airs on shield and buffer up-tilt. I should make a more formal plan
of how I want to bait him on shield. Floating and threatening bair is good, but
if you whiff bair then bad things will happen. Your options are:

Cross up nair
Falling up air
Float bair
Float b-reverse bite
Tomahawk

Also, be more cognisant of Ivysaur landing with aerials, and also using nair out
of shield. Wait a beat longer to make them nair if they are spamming it OOS. 
** 0-2 vs ScAtt
I mean, it was scatt. He gave me good advice: Against Snake, whenever he pulls a
grenade he is pressuring himself. He has to shield to drop it. React to him
pulling a grenade by taking some space. Watch the timer on every
grenade. Sometimes, just put your bike up in there when he grabs a grenade.
** 2-1 vs BlueRay
He spammed low aerials so I run up shielded him into oblivion
** 1-2 vs KAJE (KJ)
I need a better gameplan against characters that low profile well (mostly
Greninja and Joker). The first game, I was getting lots of nair combos and
racking up damage good. Also, my ledge trapping was amazing that game. He could
not get off the ledge. One thing I realized is that Battlefield kind of sucks
because I can't cover ledgehop and neutral get up with jump bite. I might just
prefer PS2. All of the things I use to start combos don't work against low
profile characters. Maybe treat this more like the Squirtle matchup. More fairs,
dtilts, grabs. 
** general notes
How does Chrom get the hit on you?

Nair high and fast fall the second hit is a really good mixup, but don't abuse
it. 

Don't immediately go for the second up tilt if the first one whiff. 
* 10/1/2019 @ Tech Chase
probably the best tournament i've played!

Round 1 was kind of a wash. I thought that it was going to go badly after
this. I play Ahbay. His Greninja is so jerky. And pretty campy, too. I needed to
play a lot more patient. It wasn't too hard to force him into a corner. Take
center and then just watch what he does next. 

Round 2 was against SOLO. I took a tight game 1, then he took game 2. I was down
a full stock game 3, but he SD'd at 20% and I ran with the momentum to take
it. If I hit Waft consistently on him, I body him. We're so even in neutral. But
Ike is really hard to kill, because I can't cover his recovery very well (note:
I think. I'd need to practice more to confirm) and he's heavy enough that bair
and dash attack and bite don't kill for a while. I need the Waft confirms real
bad. 

Round 3 was against Jason. I won 3-0 (first best of 5 in bracket!). Game 1, I
started to get antsy, but I won with a fantastic Waft read on last stock. Up
tilted him, he immediately air dodged, I hard called it out. Game 2 was also
close. Game 3 I just destroyed him. The thing with Zelda is that she is really
good at long range, because knight is legitimately unbeatable. You pretty much
just have to give her stage. And you don't want to be in her face all the time
because tilts, neutral B, pivot grab, dash back fsmash are all good at stuffing
you out. But she sucks at the mid range. She doesn't have the speed to close the
gap, and she doesn't have long aerials. Jason gets nervous and dash attacks or
run up grabs. Just keep the pressure on her -- don't let her dash back and
knight for free. Throw out fadeback fairs. Call out her dashback with fair grab
or taking more space. When she's in the corner, she really doesn't have much. 

Round 4 was against Jonah. I went in expecting to get wrecked, but game 2 and 3
were last hit. He played me way too defensively, I think. I don't know if I
would have been able to handle him approaching me. My combos were very solid,
which I think scared him into the defensive play. Plus my ledge trapping was mad
on point. I definitely made a point not to spam bite because I knew that he
wanted to read it. I remember getting a lot of full hop nair, a lot of bite
later once he realized I wasn't going to spam it, fairs. 
* 11/7/2019 @ 4o4
Deep breath for the tournament: Watch your landings. Respect disadvantage. You
have very good drift back, air dodge, and ledge options. Don't hit them unless
you earn it. Remember to hit your fast fall on nair combos. Watch what they do
when you hit their shield. Watch what they do when you float near their shield. 

** 2-0 vs SomberKing
Puff. It went good. I can't explain it but I had a bead on his weaving
patterns. Really don't hold shield against Puff. Also, hit your techs. They
reallllly want that jab lock fsmash. Fair racks up damage pretty darn
quick. She's big enough for nair combos to work. Figure out how you were
escaping pound dair, because dude said that you were. Recoveries were amazing --
go high, fade back, neutral air dodge down. Really hard for her to cover because
she is slow. 
** 0-2 vs Fatality
Lost a lost of exchanges because I didn't respect/know what was safe on
Terry. He said that I need to go for more gimps, especially against characters
with poor recovery, and edgeguards. Also, to be more aware of when my combos end
but can turn into juggle situations.
** 2-0 vs BigmamaEd
I don't remember a ton about this, except Mewtwo is a fucking big body and so
much shit works against him. Be super careful about how you recover, because
that backair is huge. 
** 0-2 vs Retro18
Definitely definitely feel like I could have beaten this guy. You need to
respect Wonder Wing. Also, respect Banjo's fair. It comes out a lot quicker than
you think. His go to ledge trap was grenade fsmash. 
* 11/11/2019 @ Tech Chase
** 0-2 vs QT
Round 1 was against QT. I didn't realize how aggressive of a player he was, but
I think that worked in my favor. My lack of gameplan isn't as easily exposed,
because I can get good stuff off of defensive openings (like nair out of
shield). One thing I couldn't quite punish was him getting out of combos with
his (down b?). He seemed to punish neutral get up at ledge really hard. I have
no idea whether his down-tilts are safe at ledge. In fact, I have no idea at all
what is safe from him. 
** 0-2 vs Shiki
This one was weird. Never heard of this guy. He played PT, and it was
solid. Kind of campy Squirtle with good combos, really hard to hit. I tried
parrying a bunch of Razor Leafs but I kept missing them and then taking 2 for my
troubles. I also think that I was parrying them too far out, so I wouldn't have
been able to punish either way. I need to be really careful around Charizard. Up
Smash out of shield really, really is that fast. I avoided him well at ledge but
that thing caught me twice. Ledge trapping Ivysaur is also really hard with all
the bullshit that Ivy has. 
** Notes
Ledge scenario: Jump and aerial to cover jump, then drift back and cover neutral
get up or roll on reaction. 

If they try to jump over you at ledge, position back so they can't get behind
you. Keep them in the corner, or catch their landing if they get aggressive. 
* 11/15/2019 @ 4o4
Overall, pretty good stuff. The friendlies weren't super helpful, but I felt
locked in during my tournament sets. And I felt like some new things were
applied. Not as many as could have been. 

For the fair stuff, I need to see what top players do to chase knockdown after
fair. Oh yeah, also don't even bother with fair at low percents. It's not safe
on hit. 

** 2-1 vs Yasu
Kind of shitty Inkling. He couldn't hit upthrow combos. He fished for a ton of
roller, which is how I lost all three stocks game one. Once I caught on, the
matchup became easier. 
** 0-2 vs QT
Fuck me, this was way worse than the first one. You can't hold shield against
Ken and wait for him to mess up. His jabs and tilts are stupid safe, you're
going to lose if you're sitting in shield most of the match. Thing is, it feels
like he has a lot of disjoints, and I don't know how to get hits on him with my
stubby little legs without using out of shield. 

I think that this is a larger problem in my game. I don't know how to get hits
on people without waiting for them to mess up. And that starts working way, way
less the better your opponents get. 
** 2-0 vs Insectoid
Some PT. His Zard was pretty impatient and couldn't ledge trap. His Squirtle was
okay, but no real combo extensions. 
** 2-0 vs Nikita
I kind of destroyed her. She couldn't set up any traps, my camping was really
good -- I didn't just not approach, I stayed in a range where she would do
something silly and then I would fair grab or nair out of shield and just get
these stupid fat punishes. I got a sick kill off the top with bike into
up-b. Also got a sweet zero to death.
** 1-2 vs DarkForce
Holy fuck, I hate playing against Villager. 
* 12/22/2019 @ GB
I played friendlies with Omega. He was very good at a couple of things:
1) Denying my combo starters. I barely got a single nair starter
2) Getting 30+ off of random hits. Seriously, a stray nair or bair and I was
   guaranteed taking 30. He knew what he could throw out in neutral that would
   lead to conversions, and he knew how to convert. 
3) Playing at the very edge of my range and capitalizing off of my whiffs. All
   of my drifting nonsense basically did nothing. I would drift in and land with
   fair, and he would do a quick dash out, dash in, and then combo me for 30+. 

Also, Joker has a nair ledge trap. I need to figure out what that covers, and if
other Joker players use it. 

How do I get out of Joker combo strings? Mostly uair strings. When I am out, how
can I land so that he doesn't grab me or side-b me?

Mantra: Patient advantage, patient disadvantage. Convert.

DQ round 1. Lost round 2 winners to a solid Wolf who beat Spike in round 1. It
was a very close set. I lost the set because I got impatient when I had a lead
in game three. Twice, at least, in the set, I became really impatient in
disadvantage and got 70+ or a stock taken. I also became impatient in how I
approached, which let him get easy hits. I am gaining a sense for when someone
else wants to be impatient, and I know how to punish that. 

I won a couple easy loser's sets. Then, I played Tyson's Peach. It went quite
well. I lost 2-0, but both games were last hit. I dropped a 3-1 lead game 2. The
reason I lost both games was because of two things:
1) Not respecting Peach bair/side-b, especially at the ledge. It comes out way
   quicker than you expect, and it has a ton of knockback
2) Impatient disadvantage, especially at the ledge. 

There was also a lack of knowledge about how Peach ledge traps, which didn't
help. I got a lot of fair from ledge. But mostly, I was being very impatient and
trying to aerial OOS against a character that is very safe on shield and eats up
OOS. 

When you run up shield a lot, or pick shield as your first defensive option out
of a landing aerial, ledge get up, whatever, people are going to grab you. 

I played a lot with Newk, but only a few Wario dittos. I asked him what he does
against projectile characters. I got this:
---
Slowly take space and force them into the corner, and then bait them out of
it. They can't play their projectile game when they can't retreat, so they are
forced to play legitimate neutral with you. Except it's not quite legitimate --
you have the advantage. At this point, play normal corner pressure. 

If they STILL want to try and camp in the corner, it's because they don't feel
pressured to leave the corner. You have to pick options that make them feel like
the corner is an unsafe place. The example he gave me was just running up and
smacking them. I am sure there are others.  
---

He also advised not to hold forward in the air. Wario is very stubby, and his
aerials will only hit if you're already on top of them. 

The last thing he said was to practice my conversions. Convert off of stray
hits, and make them less stray. Use moves that you know you can convert off of,
and know how to convert (my words, not his). Definitely figure out every way
you can possibly combo into Waft, but also figure out how to extend weird nair
starters and platform combos. 
* 1/13/2020 @ Tech Chase
I lost my round one against a Snake. My disadvantage was horrible. I'd be
playing fairly even neutral and then just lose a stock off of one off stage
interaction. I got dash attacked, tilted up close, up smash -> down smash at the
ledge. I figured out game 2 that my aerial stuff was NOT working. I'd get hit
with his grenades, and anti-aired with utilt. So I started playing a more
grounded game, getting closer to him and throwing out dtilt and ftilt to catch
his dash attacks. Running in with unreactable fair. 

Second round I played a Mario, and I wasn't in a great mindset. Just a lot of
autopilot. He wasn't scrubby, but again I had terrible disadvantage. He'd hit me
with Mario combos and easily do 60 every time, even though the rest of his game
wasn't that good. 

When I swat people out of the air with my fair, I need something better to do
next. It doesn't lead to much of anything at low percents. I can tech chase at
higher percents. Should I just do something else at low percents? But then how
can even threaten the space in front of me if I can't fair?

I got destroyed by Kenneth in round 3. Again, my disadvantage was awful. 

Kenneth mentioned pressuring people at a range where they can't react to my
fair. 

How do I know what someone's going to do? For example, when Chrom is in the
corner. He could ftilt. He could dtilt. He could jab. He could shield. He could
jump. He could buffer an aerial. He could do a landing aerial. And a lot of
those are very similar. Okay, so I see that they like to do normals. Or aerial
then normal. Ftilt and dtilt are different moves to beat out. And it seems so
arbitrary to pick one over the other. 

I kind of understand how to control space, but I generally don't understand when
people want to be there. 

How does Glutonny apply pressure to people? It feels like he's usually in his
opponent's face, crossing them up with nairs, dtilting them, chomping their
shield. I don't understand how he even gets that close, especially against (for
example) sword characters. 
